# .cds/environments/staging.yml

name: staging
description: Staging environment for EKS cluster

# Environment variables
variables:
  - name: AWS_REGION
    value: "us-east-1"
    type: string
  - name: EKS_CLUSTER_NAME
    value: "eks-cluster-staging"
    type: string
  - name: NAMESPACE
    value: "staging"
    type: string
  - name: REPLICA_COUNT
    value: "2"
    type: string
  - name: RESOURCE_LIMITS_CPU
    value: "200m"
    type: string
  - name: RESOURCE_LIMITS_MEMORY
    value: "256Mi"
    type: string

# Environment secrets (encrypted)
secrets:
  - name: AWS_ACCESS_KEY_ID
    value: "encrypted:staging-aws-access-key"
  - name: AWS_SECRET_ACCESS_KEY
    value: "encrypted:staging-aws-secret-key"
  - name: SLACK_WEBHOOK_URL
    value: "encrypted:slack-webhook-staging"
  - name: GRAFANA_ADMIN_PASSWORD
    value: "encrypted:grafana-staging-password"

# Environment permissions
permissions:
  - permission: read
    users: ["developer-team", "qa-team"]
  - permission: execute
    users: ["devops-team"]
  - permission: admin
    users: ["admin"]

# Environment keys (SSH, GPG, etc.)
keys:
  - name: deployment-key
    type: ssh
    value: "encrypted:staging-deployment-ssh-key"
