# .cds/hooks/jira-integration.yml

name: jira-integration
description: Jira integration for issue tracking and deployment notifications
type: webhook

# Jira configuration
config:
  base_url: "{{.cds.env.JIRA_BASE_URL}}"
  username: "{{.cds.env.JIRA_USERNAME}}"
  api_token: "{{.cds.env.JIRA_API_TOKEN}}"
  project_key: "DEVOPS"

# Issue creation and updates
triggers:
  - event: workflow-failure
    action: create_issue
    conditions:
      - type: workflow
        value: ["eks-deployment"]
      - type: environment
        value: ["production"]
    payload:
      fields:
        project:
          key: "{{.config.project_key}}"
        summary: "Production Deployment Failed - {{.git.branch}}"
        description: |
          Production deployment pipeline failed for branch {{.git.branch}}.
          
          **Details:**
          - Workflow: {{.cds.workflow.name}}
          - Run Number: {{.cds.workflow.run.number}}
          - Failed Job: {{.cds.workflow.failed_job}}
          - Error: {{.cds.workflow.error}}
          - Commit: {{.git.hash}}
          
          **Pipeline URL:** {{.cds.ui.url}}/project/{{.cds.project.key}}/workflow/{{.cds.workflow.name}}/run/{{.cds.workflow.run.number}}
        issuetype:
          name: "Bug"
        priority:
          name: "High"
        assignee:
          name: "{{.cds.env.JIRA_DEFAULT_ASSIGNEE}}"
        labels: ["deployment", "production", "pipeline-failure"]
        
  - event: workflow-success
    action: update_issues
    conditions:
      - type: workflow
        value: ["eks-deployment"]
      - type: environment
        value: ["production"]
    payload:
      jql: 'project = "{{.config.project_key}}" AND status != "Done" AND labels = "deployment" AND labels = "production"'
      transition: "Done"
      comment: |
        Deployment completed successfully.
        
        **Details:**
        - Branch: {{.git.branch}}
        - Commit: {{.git.hash}}
        - Pipeline: {{.cds.ui.url}}/project/{{.cds.project.key}}/workflow/{{.cds.workflow.name}}/run/{{.cds.workflow.run.number}}