# .cds/hooks/pagerduty-alerts.yml

name: pagerduty-alerts
description: PagerDuty integration for critical alerts
type: webhook

# PagerDuty configuration
config:
  integration_key: "{{.cds.env.PAGERDUTY_INTEGRATION_KEY}}"
  api_url: "https://events.pagerduty.com/v2/enqueue"

# Alert templates
templates:
  critical_failure: |
    {
      "routing_key": "{{.config.integration_key}}",
      "event_action": "trigger",
      "payload": {
        "summary": "Critical EKS Deployment Failure",
        "source": "OVH CDS",
        "severity": "critical",
        "component": "eks-deployment",
        "group": "infrastructure",
        "class": "deployment",
        "custom_details": {
          "project": "{{.cds.project.name}}",
          "workflow": "{{.cds.workflow.name}}",
          "environment": "{{.workflow.parameters.environment}}",
          "branch": "{{.git.branch}}",
          "commit": "{{.git.hash}}",
          "failed_job": "{{.cds.workflow.failed_job}}",
          "error": "{{.cds.workflow.error}}",
          "pipeline_url": "{{.cds.ui.url}}/project/{{.cds.project.key}}/workflow/{{.cds.workflow.name}}/run/{{.cds.workflow.run.number}}"
        }
      }
    }
    
  resolved: |
    {
      "routing_key": "{{.config.integration_key}}",
      "event_action": "resolve",
      "dedup_key": "eks-deployment-{{.cds.project.key}}-{{.workflow.parameters.environment}}"
    }

# Alert triggers
triggers:
  - event: workflow-failure
    template: critical_failure
    conditions:
      - type: workflow
        value: ["eks-deployment"]
      - type: environment
        value: ["production"]
      - type: job
        value: ["terraform-apply", "deploy-applications"]
        
  - event: workflow-success
    template: resolved
    conditions:
      - type: workflow
        value: ["eks-deployment"]
      - type: environment
        value: ["production"]
      - type: previous_status
        value: ["failure"]