# .cds/hooks/security-alerts.yml

name: security-alerts
description: Security alerts for critical vulnerabilities and compliance issues
type: webhook

# Security alert configuration
config:
  security_team_email: "{{.cds.env.SECURITY_TEAM_EMAIL}}"
  smtp_server: "{{.cds.env.SMTP_SERVER}}"
  smtp_port: "{{.cds.env.SMTP_PORT}}"
  smtp_username: "{{.cds.env.SMTP_USERNAME}}"
  smtp_password: "{{.cds.env.SMTP_PASSWORD}}"

# Security alert templates
templates:
  critical_vulnerability: |
    Subject: CRITICAL: Security Vulnerabilities Detected in EKS Deployment
    
    Critical security vulnerabilities have been detected during the deployment pipeline.
    
    **Project:** {{.cds.project.name}}
    **Environment:** {{.workflow.parameters.environment}}
    **Branch:** {{.git.branch}}
    **Commit:** {{.git.hash}}
    
    **Critical Issues Found:**
    {{.security_scan.critical_issues}}
    
    **High Severity Issues:**
    {{.security_scan.high_issues}}
    
    **Action Required:**
    - Review security scan reports
    - Address critical vulnerabilities immediately
    - Update dependencies and images
    
    **Pipeline URL:** {{.cds.ui.url}}/project/{{.cds.project.key}}/workflow/{{.cds.workflow.name}}/run/{{.cds.workflow.run.number}}
    
    This is an automated security alert from OVH CDS.
    
  compliance_failure: |
    Subject: COMPLIANCE ALERT: Security Compliance Check Failed
    
    Security compliance checks have failed for the EKS deployment.
    
    **Project:** {{.cds.project.name}}
    **Environment:** {{.workflow.parameters.environment}}
    **Compliance Score:** {{.security_compliance.score}}/100
    
    **Failed Checks:**
    {{.security_compliance.failed_checks}}
    
    **Recommendations:**
    {{.security_compliance.recommendations}}
    
    Please review and address the compliance issues before proceeding with production deployment.

# Security alert triggers
triggers:
  - event: job-failure
    template: critical_vulnerability
    conditions:
      - type: job
        value: ["security-scan"]
      - type: security_severity
        value: ["CRITICAL"]
      - type: environment
        value: ["production", "staging"]
        
  - event: job-failure
    template: compliance_failure
    conditions:
      - type: job
        value: ["security-compliance"]
      - type: compliance_score
        operator: "less_than"
        value: 70